### ISSUE TITLE
Installing rust as a postInstall script makes debugging nightmarish

### ISSUE THREAD

**Issue by jacobmischka** [mike-engel/now-rust#10]
Logs are eaten, resulting in opaque undebuggable failures.

**Comment by mike-engel** [comment]
Do you have a public lambda I can use, or a project/repo to reproduce?

**Comment by jacobmischka** [comment]
Sorry, I made this issue pretty terrible intentionally because I intend to send a PR once I've gotten everything working, ha.

Builds were failing with only the following error:

```
Installing build runtime...
Error: Exited with 1
    at ChildProcess.child.on (/var/task/sandbox-worker.js:26511:37)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
worker exited with code 20 and signal null
done
```

After forking the builder and calling `installRustAndFriends` explicitly in `build` I now believe the fundamental issue is because of the log below. I made a few other changes when trying to debug, so as soon as I'm sure this is the root of the problem I will send a PR.

```
Installing build runtime...
Build runtime installed: 2672.076ms
Looking up build cache...
downloading files
downloading the rust toolchain
what
warning: $HOME differs from euid-obtained home directory: you may be using sudo
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: latest update on 2019-09-26, rust version 1.38.0 (625451e37 2019-09-23)
info: downloading component 'rustc'
info: downloading component 'rust-std'
info: downloading component 'cargo'
info: downloading component 'rust-docs'
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'cargo'
info: installing component 'rust-docs'
info: default toolchain set to 'stable'

  stable installed - rustc 1.38.0 (625451e37 2019-09-23)


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH 
environment variable. Next time you log in this will be done automatically.

To configure your current shell run source $HOME/.cargo/env
installing openssl-devel...
No package krb5-libs-1.14.1-27.41.amzn1.x86_64 available.
Error: Nothing to do
failed to `yum install -y openssl-devel`
{ Error: Command failed: yum downgrade -y krb5-libs-1.14.1-27.41.amzn1.x86_64
    at makeError (/tmp/0e9a2a218d6b4dc7/.build-utils/.builder/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/tmp/0e9a2a218d6b4dc7/.build-utils/.builder/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 1,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'yum downgrade -y krb5-libs-1.14.1-27.41.amzn1.x86_64',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
```

**Comment by mike-engel** [comment]
Ahh ok then! I’ll wait for your PR. Thanks for the work on this!
