### ISSUE TITLE
The readme example is not working with now dev

### ISSUE THREAD

**Issue by wcastand** [mike-engel/now-rust#15]
**Describe the bug**
I'm trying to implement the default example in the README. but when I access `api/user` on localhost I get an error msg (see logs section)

**To Reproduce**
this is a repo of my current state : https://github.com/wcastand/example_rust_now

**Expected behavior**

**Logs**

```
~/Documents/rust/api master* 35s ❯ now dev
> Now CLI 16.5.2 dev (beta) — https://zeit.co/feedback/dev
> Ready! Available at http://localhost:3000
> Building now-rust@1.0.0:api/user.rs
downloading the rust toolchain
info: downloading installer
info: profile set to 'default'
info: updating existing rustup installation


Rust is installed now. Great!

To get started you need Cargo's bin directory ($HOME/.cargo/bin) in your PATH
environment variable. Next time you log in this will be done
automatically.

To configure your current shell run source $HOME/.cargo/env
installing openssl-devel...
failed to `yum install -y openssl-devel`
Error: spawn yum ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264:19)
    at onErrorNT (internal/child_process.js:456:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  message: 'spawn yum ENOENT',
  errno: 'ENOENT',
  code: 'ENOENT',
  syscall: 'spawn yum',
  path: 'yum',
  spawnargs: [ 'install', '-y', 'openssl-devel' ],
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'yum install -y openssl-devel',
  timedOut: false,
  killed: false
}
```

**Environment (please complete the following information):**
 - rust [e.g. stable]
 - rust edition [e.g. 2018]
 - now-rust [e.g. 1.0.1]
 - OSX Mojave (10.14.6)

**Comment by mike-engel** [comment]
Hi @wcastand, this is a known issue, and is being tracked in #1 and #3, and #6.

**Comment by wcastand** [comment]
Sorry about this, I didn't realised it was linked. my bad for the useless issue then :)
