### ISSUE TITLE
now-rust failing to compile hyper 0.12.35, cargo.lock pins it to 0.12.33

### ISSUE THREAD

**Issue by blakehawkins** [mike-engel/now-rust#17]
**Describe the bug**
A zeit.co build runner using now-rust is failing to compile on a hyper 0.12.35 step, but cargo.lock should pin hyper on 0.12.33:

```
...
     Running `rustc --crate-name hyper /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="__internal_flaky_tests"' --cfg 'feature="default"' --cfg 'feature="futures-cpupool"' --cfg 'feature="net2"' --cfg 'feature="runtime"' --cfg 'feature="tokio"' --cfg 'feature="tokio-executor"' --cfg 'feature="tokio-reactor"' --cfg 'feature="tokio-tcp"' --cfg 'feature="tokio-threadpool"' --cfg 'feature="tokio-timer"' -C metadata=baf780477bc126ad -C extra-filename=-baf780477bc126ad --out-dir /zeit/35058a40/target/release/deps -L dependency=/zeit/35058a40/target/release/deps --extern bytes=/zeit/35058a40/target/release/deps/libbytes-984ca03b6bac9032.rmeta --extern futures=/zeit/35058a40/target/release/deps/libfutures-d6d90b26a1db9345.rmeta --extern futures_cpupool=/zeit/35058a40/target/release/deps/libfutures_cpupool-7f433ef6768b85f9.rmeta --extern h2=/zeit/35058a40/target/release/deps/libh2-6bc00faae5aed06f.rmeta --extern http=/zeit/35058a40/target/release/deps/libhttp-1086d8ded4dc06f2.rmeta --extern http_body=/zeit/35058a40/target/release/deps/libhttp_body-761e17f7607fe575.rmeta --extern httparse=/zeit/35058a40/target/release/deps/libhttparse-b16dabd259454e4e.rmeta --extern iovec=/zeit/35058a40/target/release/deps/libiovec-761b16d27e507b1c.rmeta --extern itoa=/zeit/35058a40/target/release/deps/libitoa-8b90c0416aaa1224.rmeta --extern log=/zeit/35058a40/target/release/deps/liblog-04b81105fd09b8ac.rmeta --extern net2=/zeit/35058a40/target/release/deps/libnet2-2589aab84683a3d2.rmeta --extern time=/zeit/35058a40/target/release/deps/libtime-6ce88697e34eb71f.rmeta --extern tokio=/zeit/35058a40/target/release/deps/libtokio-d8945f6706dc256b.rmeta --extern tokio_buf=/zeit/35058a40/target/release/deps/libtokio_buf-07ee66150e59350e.rmeta --extern tokio_executor=/zeit/35058a40/target/release/deps/libtokio_executor-61f9fe3a74555f64.rmeta --extern tokio_io=/zeit/35058a40/target/release/deps/libtokio_io-4548faf4e9358ac2.rmeta --extern tokio_reactor=/zeit/35058a40/target/release/deps/libtokio_reactor-0c32dbb0108fae3a.rmeta --extern tokio_tcp=/zeit/35058a40/target/release/deps/libtokio_tcp-cd98b6133e77c94b.rmeta --extern tokio_threadpool=/zeit/35058a40/target/release/deps/libtokio_threadpool-2c45bc2374700c23.rmeta --extern tokio_timer=/zeit/35058a40/target/release/deps/libtokio_timer-fd26a1d177e6bc24.rmeta --extern want=/zeit/35058a40/target/release/deps/libwant-7ac25732fa945f67.rmeta --cap-lints allow -C target-cpu=ivybridge -C target-feature=-aes,-avx,+fxsr,-popcnt,+sse,+sse2,-sse3,-sse4.1,-sse4.2,-ssse3,-xsave,-xsaveopt --cfg error_source --cfg try_from`
error: macro expansion ignores token `if` and any following
   --> <::log::macros::log_impl macros>:13:23
    |
13  |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
    |                       ^^
    | 
   ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/pool.rs:382:21
    |
382 |             None => trace!("put; found waiter for {:?}", key),
    |                     -----------------------------------------
    |                     |
    |                     caused by the macro expansion here
    |                     help: you might be missing a semicolon here: `;`
    |
    = note: the usage of `log_impl!` is likely invalid in expression context
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: macro expansion ignores token `if` and any following
   --> <::log::macros::log_impl macros>:13:23
    |
13  |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
    |                       ^^
    | 
   ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:534:33
    |
534 | ...                   debug!("client connection error: {}", e)
    |                       ----------------------------------------
    |                       |
    |                       caused by the macro expansion here
    |                       help: you might be missing a semicolon here: `;`
    |
    = note: the usage of `log_impl!` is likely invalid in expression context
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: macro expansion ignores token `if` and any following
  --> <::log::macros::log_impl macros>:3:23
   |
3  |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
   |                       ^^
   | 
  ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:83:29
   |
83 | ...                   trace!("connection complete")
   |                       -----------------------------
   |                       |
   |                       caused by the macro expansion here
   |                       help: you might be missing a semicolon here: `;`
   |
   = note: the usage of `log_impl!` is likely invalid in expression context
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: macro expansion ignores token `if` and any following
  --> <::log::macros::log_impl macros>:13:23
   |
13 |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
   |                       ^^
   | 
  ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:85:38
   |
85 |                         .map_err(|e| debug!("connection error: {}", e))
   |                                      ---------------------------------
   |                                      |
   |                                      caused by the macro expansion here
   |                                      help: you might be missing a semicolon here: `;`
   |
   = note: the usage of `log_impl!` is likely invalid in expression context
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: macro expansion ignores token `if` and any following
   --> <::log::macros::log_impl macros>:13:23
    |
13  |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
    |                       ^^
    | 
   ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:142:50
    |
142 | ...                   .map_err(|e| debug!("client request body error: {}", e));
    |                                    ------------------------------------------
    |                                    |
    |                                    caused by the macro expansion here
    |                                    help: you might be missing a semicolon here: `;`
    |
    = note: the usage of `log_impl!` is likely invalid in expression context
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: macro expansion ignores token `if` and any following
   --> <::log::macros::log_impl macros>:13:23
    |
13  |     let lvl = $ lvl ; if lvl <= $ crate :: STATIC_MAX_LEVEL && lvl <= $ crate
    |                       ^^
    | 
   ::: /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/server.rs:309:26
    |
309 |             .map_err(|e| debug!("stream error: {}", e))
    |                          -----------------------------
    |                          |
    |                          caused by the macro expansion here
    |                          help: you might be missing a semicolon here: `;`
    |
    = note: the usage of `log_impl!` is likely invalid in expression context
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/pool.rs:382:21
    |
382 |             None => trace!("put; found waiter for {:?}", key),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53667
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:534:33
    |
534 | ...                   debug!("client connection error: {}", e)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53667
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:83:29
   |
83 | ...                   trace!("connection complete")
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53667
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:85:38
   |
85 |                         .map_err(|e| debug!("connection error: {}", e))
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: for more information, see https://github.com/rust-lang/rust/issues/53667
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:142:50
    |
142 | ...                   .map_err(|e| debug!("client request body error: {}", e));
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53667
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0658]: `let` expressions in this position are experimental
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/server.rs:309:26
    |
309 |             .map_err(|e| debug!("stream error: {}", e))
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: for more information, see https://github.com/rust-lang/rust/issues/53667
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/pool.rs:382:21
    |
382 |             None => trace!("put; found waiter for {:?}", key),
    |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: only supported directly in conditions of `if`- and `while`-expressions
    = note: as well as when nested within `&&` and parenthesis in those conditions
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:534:33
    |
534 | ...                   debug!("client connection error: {}", e)
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: only supported directly in conditions of `if`- and `while`-expressions
    = note: as well as when nested within `&&` and parenthesis in those conditions
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:83:29
   |
83 | ...                   trace!("connection complete")
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: only supported directly in conditions of `if`- and `while`-expressions
   = note: as well as when nested within `&&` and parenthesis in those conditions
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:85:38
   |
85 |                         .map_err(|e| debug!("connection error: {}", e))
   |                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |
   = note: only supported directly in conditions of `if`- and `while`-expressions
   = note: as well as when nested within `&&` and parenthesis in those conditions
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:142:50
    |
142 | ...                   .map_err(|e| debug!("client request body error: {}", e));
    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: only supported directly in conditions of `if`- and `while`-expressions
    = note: as well as when nested within `&&` and parenthesis in those conditions
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error: `let` expressions are not supported here
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/server.rs:309:26
    |
309 |             .map_err(|e| debug!("stream error: {}", e))
    |                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = note: only supported directly in conditions of `if`- and `while`-expressions
    = note: as well as when nested within `&&` and parenthesis in those conditions
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0271]: type mismatch resolving `<[closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:533:68: 535:30] as std::ops::FnOnce<(error::Error,)>>::Output == ()`
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:533:47
    |
533 | ...                   let bg = executor.execute(conn.map_err(|e| {
    |                                         ^^^^^^^ expected bool, found ()
    |
    = note: expected type `bool`
               found type `()`
    = note: required because of the requirements on the impl of `futures::Future` for `futures::MapErr<client::conn::Connection<<C as client::connect::Connect>::Transport, _>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/mod.rs:533:68: 535:30]>`

error[E0308]: match arms have incompatible types
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/client/pool.rs:382:21
    |
357 |  /         match value {
358 |  |             Some(value) => {
359 |  |                 // borrow-check scope...
360 |  |                 {
...    |
378 | /|                 {
379 | ||                     self.spawn_idle_interval(__pool_ref);
380 | ||                 }
    | ||_________________- this is found to be of type `()`
381 |  |             }
382 |  |             None => trace!("put; found waiter for {:?}", key),
    |  |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected (), found bool
383 |  |         }
    |  |_________- `match` arms have incompatible types
    |
    = note: expected type `()`
               found type `bool`
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0308]: mismatched types
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:83:29
   |
83 | ...                   trace!("connection complete")
   |                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   |                       |
   |                       expected (), found bool
   |                       help: try adding a semicolon: `;`
   |
   = note: expected type `()`
              found type `bool`
   = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)

error[E0308]: mismatched types
  --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:89:44
   |
89 | ...                   Err(Either::A(((), _))) => {
   |                                      ^^ expected bool, found ()
   |
   = note: expected type `bool`
              found type `()`

error[E0271]: type mismatch resolving `<futures::Then<futures::future::Select2<futures::MapErr<futures::future::Inspect<h2::client::Connection<T, proto::h2::SendBuf<<B as body::payload::Payload>::Data>>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:81:34: 84:26 cancel_tx:_]>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:85:34: 85:71]>, futures::MapErr<futures::Map<futures::stream::StreamFuture<futures::sync::mpsc::Receiver<_>>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:75:30: 78:26]>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:79:34: 79:84]>>, futures::future::Either<futures::Done<(), bool>, futures::MapErr<futures::future::Inspect<h2::client::Connection<T, proto::h2::SendBuf<<B as body::payload::Payload>::Data>>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:81:34: 84:26 cancel_tx:_]>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:85:34: 85:71]>>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:87:31: 101:26]> as futures::Future>::Error == ()`
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:102:35
    |
102 |                     self.executor.execute(fut)?;
    |                                   ^^^^^^^ expected bool, found ()
    |
    = note: expected type `bool`
               found type `()`

error[E0308]: mismatched types
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:147:64
    |
147 | ...                   Ok(Async::Ready(())) | Err(()) => (),
    |                                                  ^^ expected bool, found ()
    |
    = note: expected type `bool`
               found type `()`

error[E0271]: type mismatch resolving `<futures::Then<futures::MapErr<proto::h2::PipeToSendStream<B>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:142:46: 142:92]>, std::result::Result<(), bool>, [closure@/zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:150:62: 153:46 conn_drop_ref:_]> as futures::Future>::Error == ()`
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/client.rs:154:55
    |
154 | ...                   self.executor.execute(pipe)?;
    |                                     ^^^^^^^ expected bool, found ()
    |
    = note: expected type `bool`
               found type `()`

error[E0308]: mismatched types
   --> /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/proto/h2/server.rs:308:9
    |
307 |       fn poll(&mut self) -> Poll<Self::Item, Self::Error> {
    |                             ----------------------------- expected `std::result::Result<futures::Async<()>, ()>` because of return type
308 | /         self.poll2()
309 | |             .map_err(|e| debug!("stream error: {}", e))
    | |_______________________________________________________^ expected (), found bool
    |
    = note: expected type `std::result::Result<_, ()>`
               found type `std::result::Result<_, bool>`

error: aborting due to 26 previous errors

Some errors have detailed explanations: E0271, E0308, E0658.
For more information about an error, try `rustc --explain E0271`.
error: could not compile `hyper`.

Caused by:
  process didn't exit successfully: `rustc --crate-name hyper /zeit/.cargo/registry/src/github.com-1ecc6299db9ec823/hyper-0.12.35/src/lib.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts --crate-type lib --emit=dep-info,metadata,link -C opt-level=3 --cfg 'feature="__internal_flaky_tests"' --cfg 'feature="default"' --cfg 'feature="futures-cpupool"' --cfg 'feature="net2"' --cfg 'feature="runtime"' --cfg 'feature="tokio"' --cfg 'feature="tokio-executor"' --cfg 'feature="tokio-reactor"' --cfg 'feature="tokio-tcp"' --cfg 'feature="tokio-threadpool"' --cfg 'feature="tokio-timer"' -C metadata=baf780477bc126ad -C extra-filename=-baf780477bc126ad --out-dir /zeit/35058a40/target/release/deps -L dependency=/zeit/35058a40/target/release/deps --extern bytes=/zeit/35058a40/target/release/deps/libbytes-984ca03b6bac9032.rmeta --extern futures=/zeit/35058a40/target/release/deps/libfutures-d6d90b26a1db9345.rmeta --extern futures_cpupool=/zeit/35058a40/target/release/deps/libfutures_cpupool-7f433ef6768b85f9.rmeta --extern h2=/zeit/35058a40/target/release/deps/libh2-6bc00faae5aed06f.rmeta --extern http=/zeit/35058a40/target/release/deps/libhttp-1086d8ded4dc06f2.rmeta --extern http_body=/zeit/35058a40/target/release/deps/libhttp_body-761e17f7607fe575.rmeta --extern httparse=/zeit/35058a40/target/release/deps/libhttparse-b16dabd259454e4e.rmeta --extern iovec=/zeit/35058a40/target/release/deps/libiovec-761b16d27e507b1c.rmeta --extern itoa=/zeit/35058a40/target/release/deps/libitoa-8b90c0416aaa1224.rmeta --extern log=/zeit/35058a40/target/release/deps/liblog-04b81105fd09b8ac.rmeta --extern net2=/zeit/35058a40/target/release/deps/libnet2-2589aab84683a3d2.rmeta --extern time=/zeit/35058a40/target/release/deps/libtime-6ce88697e34eb71f.rmeta --extern tokio=/zeit/35058a40/target/release/deps/libtokio-d8945f6706dc256b.rmeta --extern tokio_buf=/zeit/35058a40/target/release/deps/libtokio_buf-07ee66150e59350e.rmeta --extern tokio_executor=/zeit/35058a40/target/release/deps/libtokio_executor-61f9fe3a74555f64.rmeta --extern tokio_io=/zeit/35058a40/target/release/deps/libtokio_io-4548faf4e9358ac2.rmeta --extern tokio_reactor=/zeit/35058a40/target/release/deps/libtokio_reactor-0c32dbb0108fae3a.rmeta --extern tokio_tcp=/zeit/35058a40/target/release/deps/libtokio_tcp-cd98b6133e77c94b.rmeta --extern tokio_threadpool=/zeit/35058a40/target/release/deps/libtokio_threadpool-2c45bc2374700c23.rmeta --extern tokio_timer=/zeit/35058a40/target/release/deps/libtokio_timer-fd26a1d177e6bc24.rmeta --extern want=/zeit/35058a40/target/release/deps/libwant-7ac25732fa945f67.rmeta --cap-lints allow -C target-cpu=ivybridge -C target-feature=-aes,-avx,+fxsr,-popcnt,+sse,+sse2,-sse3,-sse4.1,-sse4.2,-ssse3,-xsave,-xsaveopt --cfg error_source --cfg try_from` (exit code: 1)
warning: build failed, waiting for other jobs to finish...
error: build failed
failed to `cargo build`
{ Error: Command failed: cargo build --verbose --release
    at makeError (/zeit/110dcb3f53521caf/.build-utils/.builder/node_modules/execa/index.js:174:9)
    at Promise.all.then.arr (/zeit/110dcb3f53521caf/.build-utils/.builder/node_modules/execa/index.js:278:16)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  code: 101,
  stdout: null,
  stderr: null,
  failed: true,
  signal: null,
  cmd: 'cargo build --verbose --release',
  timedOut: false,
  killed: false }
worker exited with code 20 and signal null
done
```

```
[[package]]
name = "lambda_runtime_client"
version = "0.2.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "failure 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "http 0.1.18 (registry+https://github.com/rust-lang/crates.io-index)",
 "hyper 0.12.33 (registry+https://github.com/rust-lang/crates.io-index)",
 "lambda_runtime_errors 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde 1.0.99 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_derive 1.0.99 (registry+https://github.com/rust-lang/crates.io-index)",
 "serde_json 1.0.40 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio 0.1.22 (registry+https://github.com/rust-lang/crates.io-index)",
]

[[package]]
name = "lambda_runtime_core"
version = "0.1.2"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "backtrace 0.3.35 (registry+https://github.com/rust-lang/crates.io-index)",
 "chrono 0.4.7 (registry+https://github.com/rust-lang/crates.io-index)",
 "failure 0.1.5 (registry+https://github.com/rust-lang/crates.io-index)",
 "hyper 0.12.33 (registry+https://github.com/rust-lang/crates.io-index)",
 "lambda_runtime_client 0.2.2 (registry+https://github.com/rust-lang/crates.io-index)",
 "lambda_runtime_errors 0.1.1 (registry+https://github.com/rust-lang/crates.io-index)",
 "log 0.4.8 (registry+https://github.com/rust-lang/crates.io-index)",
 "rustc_version 0.2.3 (registry+https://github.com/rust-lang/crates.io-index)",
 "tokio 0.1.22 (registry+https://github.com/rust-lang/crates.io-index)",
]
```

**To Reproduce**
If now-rust doesn't pin, and hyper releases a fix for this, it may not be reproducible, but the symptoms will come back for future issues.

**Expected behavior**
now-rust deploy CI should not build any version of any code not present in Cargo.lock

**Logs**
See above

**Environment (please complete the following information):**
 - rust stable 2018 1.39.0
 - now-rust - unknown, now.json pasted below:

```
{
	"version": 2,
	"builds": [
		{
			"src": "Cargo.toml",
			"use": "now-rust"
		}
	],
	"routes": [
		{ "src": "/", "dest": "/blakehawkins-info" }
	]
}

```

**Additional context**
Redeploy did not fix the issue.

**Comment by blakehawkins** [comment]
False alarm - Cargo.lock was .gitignored 🤦‍♂
