### ISSUE TITLE
TypeError with example

### ISSUE THREAD

**Issue by cenguidanos** [mike-engel/now-rust#36]
**Describe the bug**
Don't build the serverless function

**To Reproduce**
Implement the example of README.md

**Logs**

```bash
Vercel CLI 21.2.3 dev (beta) — https://vercel.com/feedback
> Ready! Available at http://localhost:8080
> Building now-rust@2.0.0:api/v3/index.rs
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received undefined
    at validateString (internal/validators.js:124:11)
    at Object.join (path.js:375:7)
    at Object.build (C:\Users\Desarrollo\AppData\Local\com.vercel.cli\Cache\dev\builders\node_modules\now-rust\dist\index.js:134:33)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async processMessage (C:\Users\Desarrollo\AppData\Roaming\npm\node_modules\vercel\dist\builder-worker.js:39:18) {    
  code: 'ERR_INVALID_ARG_TYPE'
}
```

**Environment:**
 - rust: 1.49.0 (e1884a8e3 2020-12-29)
 - now-rust: 2.0.4

**Comment by Borber** [comment]
Hello friend, how to solve this problem?
